/**
 * Populate DB with sample data on server start
 * to disable, edit config/environment/index.js, and set `seedDB: false`
 */

'use strict';

var Item = require('../api/item/item.model');
var User = require('../api/user/user.model');

Item.find({}).remove(function() {
    Item.create({
        /* ------------------- SCHOOLS  -------------------- */
        name: "Academy of the Pacific",
        yelpName: "",
        image: "/assets/images/a.png",
        category: "schools",
        address: "913 Alewa Drive Honolulu, HI 96817",
        website: "www.aop.net",
        gradeLevels: "6 - 12",
        enrollment: "143",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Independent",
        town: ["any town", "Honolulu"],
        student: ["middle schooler", "high school"],
        city: "Honolulu",
        writeUp: "In general, one's social life as a first-year student tends to revolve around one's 1L section. Because the sections are so large, any activity in which 1L students participate will inevitably have fellow sectionmates, and the tendency to stick with these new friends and cohorts is quite difficult to overcome. Some of HLS's policies and programs, rather than working against this tendency, actually reinforce it. For instance, each section has $12,000 to spend on activities. These activities are sometimes open to the public (for instance, lectures), but are more often insulated by section. HL Central's 1L Cup, which pits the seven 1L sections against one another in cookie-eating, balloon-popping, and pretzel-passing contests, brings the whole class together, but in a way that solidifies bonds within each section and not among them. Still, this section camaraderie, by and large, is a positive aspect of life at Harvard Law School. Section parties and other get-togethers are frequent and provide a chance for extensive social interaction for even the shiest of law students. Upper-class students say that they have stayed friends with their former sectionmates, and professors and students alike note that one's section fellows will serve as career contacts in the future.",
        logo: "../assets/images/sja-logo.jpg"
        }, {
        name: "Adventist Malama Elementary School",
        yelpName: "adventist-malama-elementary-school-waianae",
        image: "/assets/images/b.png",
        category: "schools",
        address: "86-072 Farrington Hwy, Waianae, HI 96792",
        website: "http://abcwd.com/ames",
        gradeLevels: "K - 8",
        enrollment: "57",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Seventh-day Adventist",
        town: ["any town", "Waianae", "Maiili"],
        student: ["elementary student", "middle schooler"],
        city: "Waianae",
        writeUp: "Malama Adventist Elementary school and Daycare in Waianae (one block west of Long’s) provides a high quality Preschool through 8 education program in the Christian tradition which emphasizes the lordship of Jesus Christ over all areas of life. It also prepares students spiritually, socially, academically, and physically to serve society effectively and glorify God by honoring Him in all aspects of life. Today, our school offers a broad educational program including core curricular subjects as well as Bible, art, music, computer science, physical education, and many co-curricular activities. An elementary education at our Christian Elementary campus provides strong academics in the basics of reading, language arts and mathematics as well as a solid foundation in social studies, science and health all taught from a Bible-based perspective. Various classroom activities and school events provide colorful avenues for student creativity and leadership. Daily Bible instruction and prayer, Scripture memorization, weekly chapel services and positive adult Christian role models all help each child seek and develop a growing relationship with God Malama Adventist Christian elementary school and Day-Care offer children a safe, positive and encouraging educational environment.",
        logo: "../assets/images/sja-logo.jpg"
        }, {
        name: "Saint Jerome's Academy",
        yelpName: "american-renaissance-academy-kapolei",
        image: "/assets/images/c.png",
        category: "schools",
        address: "P.O. Box 75357 Kapolei, HI 96707",
        telephone: "(808) 682-7337",
        website: "www.arahawaii.org",
        gradeLevels: "PK - 12",
        enrollment: "87",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Independent",
        town: ["any town", "Kapolei", "Ewa Beach", "Waianae"],
        student: ["preschooler", "elementary student", "middle schooler", "high schooler"],
        city: "Kapolei",
        writeUp: "In general, one's social life as a first-year student tends to revolve around one's 1L section. Because the sections are so large, any activity in which 1L students participate will inevitably have fellow sectionmates, and the tendency to stick with these new friends and cohorts is quite difficult to overcome. Some of HLS's policies and programs, rather than working against this tendency, actually reinforce it. For instance, each section has $12,000 to spend on activities. These activities are sometimes open to the public (for instance, lectures), but are more often insulated by section. HL Central's 1L Cup, which pits the seven 1L sections against one another in cookie-eating, balloon-popping, and pretzel-passing contests, brings the whole class together, but in a way that solidifies bonds within each section and not among them. Still, this section camaraderie, by and large, is a positive aspect of life at Harvard Law School. Section parties and other get-togethers are frequent and provide a chance for extensive social interaction for even the shiest of law students. Upper-class students say that they have stayed friends with their former sectionmates, and professors and students alike note that one's section fellows will serve as career contacts in the future. ",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Assets School",
        yelpName: "assets-school-honolulu",
        image: "/assets/images/d.png",
        category: "schools",
        address: "1 Ohana Nui Way Honolulu, HI 96818",
        telephone: "(808) 423-1356",
        website: "www.assets-school.net",
        gradeLevels: "K - 12",
        enrollment: "344",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Independent",
        town: ["any town", "Honolulu"],
        student: ["elementary student", "middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Calvary Chapel Christian School",
        yelpName: "calvary-chapel-christian-school-aiea",
        description: "Here is a sample description",
        image: "/assets/images/e.png",
        category: "schools",
        writeUp: "Here is a sample write up",
        address: "98-1016 Komo Mai Dr. Aiea, HI 96701",
        telephone: "(808) 524-0846",
        website: "www.cccsofhonolulu.org",
        gradeLevels: "K - 12",
        enrollment: "173",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Aiea", "Pearl City"],
        student: ["elementary student", "middle schooler", "high schooler"],
        city: "Aiea",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Cathedral Catholic Academy",
        yelpName: "",
        image: "/assets/images/f.png",
        category: "schools",
        address: "1728 Nuuanu Avenue Honolulu HI 96817",
        telephone: "(808) 533-2069",
        website: "http://teacherweb.com/HI/CathedralCatholicAcademy/HomePage/sdhp1.aspx",
        gradeLevels: "K - 8",
        enrollment: "145",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Honolulu"],
        student: ["elementary student", "middle schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Central Union Church Preschool and Kindergarten",
        yelpName: "central-union-church-preschool-and-kindergarten-honolulu",
        image: "/assets/images/g.png",
        category: "schools",
        address: "1660 South Beretania Street, 202 Honolulu, HI 96826",
        telephone: "(808) 946-4025",
        website: "www.centralunionpreschool.org",
        gradeLevels: "PK - K",
        enrollment: "180",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Congregational",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Central Christian School Mililani",
        yelpName: "central-christian-school-mililani",
        image: "/assets/images/h.png",
        category: "schools",
        address: "95-388 Wikao S. Mililani, HI 96789",
        telephone: "(808) 625-5055",
        website: "www.centralchristianschooloahu.org",
        gradeLevels: "PK - K",
        enrollment: "56",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Mililani"],
        student: ["preschooler", "elementary student"],
        city: "Mililani",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "The Children's House",
        yelpName: "the-childrens-house-pearl-city",
        image: "/assets/images/i.png",
        category: "schools",
        address: "1840 Komo Mai Drive Pearl City, HI 96782",
        telephone: "(808) 455-4131",
        website: "www.childrenshousehawaii.org",
        gradeLevels: "PK - 6",
        enrollment: "288",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Nondenominational",
        town: ["any town", "Pearl City", "Aiea"],
        student: ["preschooler", "elementary student"],
        city: "Pearl City",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Christian Academy Honolulu",
        yelpName: "christian-academy-honolulu",
        image: "/assets/images/j.png",
        category: "schools",
        address: "3400 Moanalua Road Honolulu, HI 96819",
        telephone: "(808) 836-0233",
        website: "www.capatriots.org",
        gradeLevels: "PK - 12",
        enrollment: "323",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Honolulu", "Aiea", "Pearl City"],
        student: ["preschooler", "elementary student", "middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Damien Memorial High School",
        yelpName: "damien-memorial-high-school-honolulu",
        image: "/assets/images/k.png",
        category: "schools",
        address: "1401 Houghtailing Street Honolulu, HI 96817",
        telephone: "(808) 841-0195",
        website: "www.damien.edu",
        gradeLevels: "6 - 12",
        enrollment: "642",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Honolulu"],
        student: ["middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Friendship Christian Schools",
        yelpName: "friendship-christian-schools-ewa-beach",
        image: "/assets/images/l.png",
        category: "schools",
        address: "91-1130 Renton Road Ewa Beach, HI 96706",
        telephone: "(808) 681-8838",
        website: "www.friendshipministries.org",
        gradeLevels: "PK - 12",
        enrollment: "287",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Baptist",
        town: ["any town", "Ewa Beach", "Kapolei"],
        student: ["preschooler", "elementary student", "middle schooler", "high schooler"],
        city: "Ewa Beach",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Hanahauoli School",
        yelpName: "hanahauoli-school-honolulu",
        image: "/assets/images/m.png",
        category: "schools",
        address: "1922 Makiki Street Honolulu, HI 96822",
        telephone: "(808) 949-6461",
        website: "www.hanahauoli.org",
        gradeLevels: "PK - 6",
        enrollment: "210",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Independent",
        town: ["any town", "Honolulu", "Manoa"],
        student: ["preschooler", "elementary student"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Hanalani Schools",
        yelpName: "hanalani-schools-mililani",
        image: "/assets/images/n.png",
        category: "schools",
        address: "94-294 Anania Drive Mililani, HI 96789",
        telephone: "(808) 625-0737 ext. 456",
        website: "www.hanalani.org",
        gradeLevels: "PK - 12",
        enrollment: "715",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Nondenominational",
        town: ["any town", "Mililani"],
        student: ["preschooler", "elementary student", "middle schooler", "high schooler"],
        city: "Mililani",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Hawaii Baptist Academy",
        yelpName: "hawaii-baptist-academy-honolulu",
        image: "/assets/images/o.png",
        category: "schools",
        address: "Administrative Offices Honolulu, HI 96817",
        telephone: "(808) 595-5000",
        website: "www.hba.net",
        gradeLevels: "K - 12",
        enrollment: "1096",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Baptist",
        town: ["any town", "Honolulu"],
        student: ["elementary student", "middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Hawaiian Mission Academy",
        yelpName: "hawaiian-mission-elementary-and-intermediate-school-honolulu?osq=hawaiian+mission+acadmey",
        image: "/assets/images/p.png",
        category: "schools",
        address: "1415 Makiki Street Honolulu, HI 96814",
        telephone: "(808) 949-2033",
        website: "www.hmak8.org",
        gradeLevels: "K - 8",
        enrollment: "112",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Seventh-day Adventist",
        town: ["any town", "Honolulu"],
        student: ["elementary student", "middle schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Hawaiian Mission Academy",
        yelpName: "hawaiian-mission-academy-honolulu",
        image: "/assets/images/a.png",
        category: "schools",
        address: "1438 Pensacola Street Honolulu, HI 96822",
        telephone: "(808) 536-2207",
        website: "http://hma4u.org/",
        gradeLevels: "9 - 12",
        enrollment: "122",
        boarding: "Day & Boarding",
        gender: "Co-ed",
        religion: "Seventh-day Adventist",
        town: ["any town", "Honolulu"],
        student: ["high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Hawaiian Mission Academy Windward Campus",
        image: "/assets/images/b.png",
        category: "schools",
        address: "160 Mookua Street Kailua, HI 96734",
        telephone: "(808) 261-0565",
        website: "www.hmawindward.org",
        gradeLevels: "K - 8",
        enrollment: "122",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Seventh-day Adventist",
        town: ["any town", "Kailua", "Kaneohe"],
        student: ["elementary student", "middle schooler"],
        city: "Kailua",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Hoala School",
        yelpName: "hoala-school-wahiawa-2",
        image: "/assets/images/c.png",
        category: "schools",
        address: "1067 A California Avenue Wahiawa, HI 96786",
        telephone: "(808) 621-1898",
        website: "www.hoalaschool.org",
        gradeLevels: "K - 12",
        enrollment: "83",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Nondenominational",
        town: ["any town", "Wahiawa"],
        student: ["elementary student", "middle schooler", "high schooler"],
        city: "Wahiawa",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Hoaloha O Ke Kai Montessori School",
        yelpName: "hoaloha-o-ke-kai-montessori-school-honolulu",
        image: "/assets/images/d.png",
        category: "schools",
        address: "1339 Hunakai Street Honolulu, HI 96825",
        telephone: "(808) 735-5165",
        website: "http://hoalohaokekai.org/",
        gradeLevels: "EC - 6",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Holy Family Catholic Academy",
        yelpName: "",
        image: "/assets/images/e.png",
        category: "schools",
        address: "830 Main St. Honolulu, HI 96818",
        telephone: "(808) 423-9611",
        website: "http://www.hfcahawaii.org/pages/Holy_Family_Catholic_Academy",
        gradeLevels: "PK - 8",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Holy Nativity School",
        yelpName: "holy-nativity-school-honolulu",
        image: "/assets/images/f.png",
        category: "schools",
        address: "5286 Kalaniana`ole Highway Honolulu, HI 96821",
        telephone: "(808) 373-3232",
        website: "www.holynativityschool.org",
        gradeLevels: "PK - 6",
        enrollment: "151",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Episcopal",
        town: ["any town", "Honolulu", "Hawaii Kai"],
        student: ["preschooler", "elementary student"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Hongwanji Mission School",
        yelpName: "hongwanji-mission-school-honolulu",
        image: "/assets/images/g.png",
        category: "schools",
        address: "1728 Pali Highway Honolulu, HI 96813",
        telephone: "(808) 532-0522",
        website: "www.hongwanjimissionschool.org",
        gradeLevels: "PK - 8",
        enrollment: "339",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Buddhist",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Honolulu Waldorf School",
        yelpName: "honolulu-waldorf-school-honolulu-2",
        image: "/assets/images/h.png",
        category: "schools",
        address: "350 Ulua Street Honolulu, HI 96821",
        telephone: "(808) 377-5471",
        website: "www.honoluluwaldorf.org",
        gradeLevels: "PK - 12",
        enrollment: "300",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Nondenominational",
        town: ["any town", "Honolulu", "Kahala", "Hawaii Kai"],
        student: ["preschooler", "elementary student", "middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Huakailani School for Girls",
        image: "/assets/images/i.png",
        category: "schools",
        address: "146 Hekili St., Suite 104 Kailua, HI 96734",
        telephone: "(808) 315-9374",
        website: "www.huakailani.org",
        gradeLevels: "K - 6",
        enrollment: "25",
        boarding: "Day Only",
        gender: "Girls Only",
        religion: "Independent",
        town: ["any town", "Kailua", "Kaneohe"],
        student: ["elementary student"],
        city: "Kailua",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Iolani School",
        yelpName: "iolani-school-honolulu",
        image: "/assets/images/j.png",
        category: "schools",
        address: "563 Kamoku Street Honolulu, HI 96826",
        telephone: "(808) 949-5355",
        website: "www.iolani.org",
        gradeLevels: "K - 12",
        enrollment: "1890",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Episcopal",
        town: ["any town", "Honolulu"],
        student: ["elementary student", "middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Island Pacific Academy",
        yelpName: "island-pacific-academy-kapolei",
        image: "/assets/images/k.png",
        category: "schools",
        address: "909 Haumea Street Kapolei, HI 96707",
        telephone: "(808) 674-3563",
        website: "www.ipahawaii.org",
        gradeLevels: "PK - 12",
        enrollment: "503",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Independent",
        town: ["any town", "Kapolei", "Ewa Beach"],
        student: ["preschooler", "elementary student", "middle schooler", "high schooler"],
        city: "Kapolei",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Kailua Christian Academy",
        yelpName: "",
        image: "/assets/images/l.png",
        category: "schools",
        address: "1110 A Kailua Roadd, Kailua HI 96734",
        telephone: "(808) 263-9999",
        website: "",
        gradeLevels: "PK - 12",
        enrollment: "68",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Protestant",
        town: ["any town", "Kailua", "Kaneohe"],
        student: ["preschooler", "elementary student", "middle schooler", "high schooler"],
        city: "Kailua",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Kaimuki Christian School", 
        yelpName: "kaimuki-christian-school-honolulu",
        image: "/assets/images/m.png",
        category: "schools",
        address: "1117 Koko Head Avenue Honolulu, HI 96816",
        telephone: "(808) 732-1781",
        website: "www.kaimukichristianschool.org",
        gradeLevels: "PK - 11",
        enrollment: "321",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Honolulu", "Kahala"],
        student: ["preschooler", "elementary student", "middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Kamehameha Schools",
        yelpName: "kamehameha-schools-honolulu-2?osq=Kamehameha+School",
        image: "/assets/images/n.png",
        category: "schools",
        address: "1887 Makuakane Street Honolulu, HI 96817-1887",
        telephone: "(808) 842-8211",
        website: "www.ksbe.edu",
        gradeLevels: "K - 12",
        enrollment: "3192",
        boarding: "Day & Boarding",
        gender: "Co-ed",
        religion: "Protestant",
        town: ["any town", "Honolulu"],
        student: ["elementary student", "middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Kawaiahao Church School",
        yelpName: "kawaiahao-church-school-honolulu",
        image: "/assets/images/o.png",
        category: "schools",
        address: "872 Mission Lane Honolulu, HI 96813",
        telephone: "(808) 585-0622",
        website: "www.kawaiahaoschool.org",
        gradeLevels: "EC - 5",
        enrollment: "69",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Congregational",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Koolau Baptist Academy",
        yelpName: "koolau-baptist-academy-kaneohe",
        image: "/assets/images/p.png",
        category: "schools",
        address: "45-633 Keneke Street, P.O. Box 1642 Kaneohe, HI 96744",
        telephone: "(808) 233-2900",
        website: "koolaubc.org",
        gradeLevels: "K - 12",
        enrollment: "172",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Baptist",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["elementary student", "middle schooler", "high schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "La Pietra Hawaii School for Girls",
        yelpName: "la-pietra-hawaii-school-for-girls-honolulu",
        image: "/assets/images/a.png",
        category: "schools",
        address: "2933 Poni Moi Road Honolulu, HI 96815",
        telephone: "(808) 922-2744",
        website: "www.lapietra.edu",
        gradeLevels: "6 - 12",
        enrollment: "200",
        boarding: "Day Only",
        gender: "Girls Only",
        religion: "Independent",
        town: ["any town", "Honolulu", "Kahala"],
        student: ["middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Lanakila Baptist School",
        yelpName: "lanakila-baptist-school-ewa-beach",
        image: "/assets/images/b.png",
        category: "schools",
        address: "94-1250 Waipahu Street Waipahu, HI 96797",
        telephone: "(808) 677-0731",
        website: "www.lanakilabaptist.org",
        gradeLevels: "K - 12",
        enrollment: "161",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Baptist",
        town: ["any town", "Waipahu", "Ewa Beach"],
        student: ["elementary student", "middle schooler", "high schooler"],
        city: "Waipahu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Le Jardin Academy",
        yelpName: "le-jardin-academy-kailua",
        image: "/assets/images/c.png",
        category: "schools",
        address: "917 Kalanianaole Hwy. Kailua, HI 96734",
        telephone: "(808) 261-0707 ext. 1310",
        website: "www.lejardinacademy.org",
        gradeLevels: "PK - 12",
        enrollment: "818",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Independent",
        town: ["any town", "Kailua", "Kaneohe"],
        student: ["preschooler", "elementary student", "middle schooler", "high schooler"],
        city: "Kailua",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Lutheran High School",
        yelpName: "lutheran-high-school-of-hawaii-honolulu",
        image: "/assets/images/d.png",
        category: "schools",
        address: "1404 University Avenue Honolulu, HI 96822",
        telephone: "(808) 949-5302",
        website: "www.lhshawaii.org",
        gradeLevels: "6 - 12",
        enrollment: "50",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Lutheran",
        town: ["any town", "Honolulu", "Manoa"],
        student: ["middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Maili Bible School",
        yelpName: "maili-bible-church-and-school-waianae",
        image: "/assets/images/e.png",
        category: "schools",
        address: "87-138 Gilipake Street Waianae, HI 96792",
        telephone: "(808) 696-3038",
        website: "www.mailibibleschool.org",
        gradeLevels: "K - 12",
        enrollment: "71",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Nondenominational",
        town: ["any town", "Waianae", "Maiili"],
        student: ["elementary student", "middle schooler", "high schooler"],
        city: "Waianae",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Maryknoll School",
        yelpName: "maryknoll-school-honolulu",
        image: "/assets/images/f.png",
        category: "schools",
        address: "1526 Alexander Street Honolulu, HI 96822",
        telephone: "(808) 952-7330",
        website: "www.maryknollschool.org",
        gradeLevels: "K - 12",
        enrollment: "1362",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Honolulu"],
        student: ["elementary student", "middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Mid-Pacific Institue",
        yelpName: "mid-pacific-institute-honolulu",
        image: "/assets/images/g.png",
        category: "schools",
        address: "2445 Kaala Street Honolulu, HI 96822-2299",
        telephone: "(808) 973-5025",
        website: "www.midpac.edu",
        gradeLevels: "PK - 12",
        enrollment: "1553",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Independent",
        town: ["any town", "Honolulu", "Manoa"],
        student: ["elementary student", "middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Montessori Community School",
        yelpName: "montessori-community-school-honolulu",
        image: "/assets/images/h.png",
        category: "schools",
        address: "1239 Nehoa Street Honolulu, HI 96822-3071",
        telephone: "(808) 522-0244",
        website: "montessorihawaii.org",
        gradeLevels: "PK - 6",
        enrollment: "169",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Independent",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Navy Hale Keiki School",
        yelpName: "navy-hale-keiki-school-honolulu-2",
        image: "/assets/images/i.png",
        category: "schools",
        address: "153 Bougainville Drive Honolulu, HI 96818",
        telephone: "(808) 423-1727",
        website: "www.nhks.org/www.ohana.nhks.org",
        gradeLevels: "PK - 4",
        enrollment: "229",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Independent",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "New Hope Christian School",
        yelpName: "new-hope-christian-school-waipahu",
        image: "/assets/images/j.png",
        category: "schools",
        address: "94-050 Farrington Hwy., Suite C-2 Waipahu, HI 96707",
        telephone: "(808) 678-3776",
        website: "http://www.newhopeleeward.org/school",
        gradeLevels: "EC - 8",
        enrollment: "186",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Waipahu", "Ewa Beach"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Waipahu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Our Redeemer Lutheran School",
        yelpName: "our-redeemer-lutheran-school-honolulu",
        image: "/assets/images/k.png",
        category: "schools",
        address: "2428 Wilder Ave. Honolulu, HI 96822",
        telephone: "(808)945-7765",
        website: "www.orls-hi.org",
        gradeLevels: "PK - 8",
        enrollment: "186",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Lutheran",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Our Lady of Good Counsel School",
        yelpName: "our-lady-of-good-counsel-school-pearl-city",
        image: "/assets/images/l.png",
        category: "schools",
        address: "1530 Hoolana St. Pearl City, HI 96782",
        telephone: "(808)455-4533",
        website: "",
        gradeLevels: "PK - 8",
        enrollment: "280",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Pearl City", "Aiea"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Pearl City",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Our Lady of Perpetual Help School",
        yelpName: "our-lady-of-perpetual-help-school-ewa-beach",
        image: "/assets/images/m.png",
        category: "schools",
        address: "91-1010 N. Road Ewa Beach, HI 96706",
        telephone: "(808)689-0474",
        website: "",
        gradeLevels: "K - 8",
        enrollment: "222",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Ewa Beach"],
        student: ["elementary student", "middle schooler"],
        city: "Ewa Beach",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Our Savior Lutheran School",
        yelpName: "our-savior-lutheran-school-aiea",
        image: "/assets/images/n.png",
        category: "schools",
        address: "98-1098 Moanalua Road Aiea, HI 96701",
        telephone: "(808) 488-0000",
        website: "www.osls-hawaii.org",
        gradeLevels: "PK - 8",
        enrollment: "161",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Lutheran",
        town: ["any town", "Aiea", "Pearl City"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Aiea",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Pacific Buddhist Academy",
        yelpName: "pacific-buddhist-academy-honolulu",
        image: "/assets/images/o.png",
        category: "schools",
        address: "1710 Pali Highway Honolulu, HI 96813",
        telephone: "(808) 532-2649",
        website: "www.PacificBuddhistAcademy.org",
        gradeLevels: "9 - 12",
        enrollment: "70",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Buddhist",
        town: ["any town", "Honolulu"],
        student: ["high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Pearl Harbor Christian Academy",
        yelpName: "pearl-harbor-christian-academy-honolulu-2",
        image: "/assets/images/p.png",
        category: "schools",
        address: "94-1044 Waipio Uka St. Waipahu, HI 96797",
        telephone: "(808) 678-3997",
        website: "calvarychapelpearlharbor.com/phca.html",
        gradeLevels: "PK - 8",
        enrollment: "200",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Waipahu", "Pearl CIty", "Aiea"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Waipahu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Playmate Kindergarten, Day Care Center & Grade School, Ltd.",
        yelpName: "playmate-kindergarten-day-care-ctr-and-grde-schl-ltd-honolulu",
        image: "/assets/images/a.png",
        category: "schools",
        address: "1704 Keeaumoku Street Honolulu, HI 96822",
        telephone: "(808) 536-6442",
        gradeLevels: "PK - 3",
        enrollment: "15",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Independent",
        town: ["any town", "Waianae", "Maiili"],
        student: ["preschooler", "elementary student"],
        city: "Waianae",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Punahou School",
        yelpName: "punahou-school-honolulu",
        image: "/assets/images/b.png",
        category: "schools",
        address: "1601 Punahou Street Honolulu, HI 96822",
        telephone: "(808) 944-5711",
        website: "www.punahou.edu",
        gradeLevels: "K - 12",
        enrollment: "3762",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Nondenominational",
        town: ["any town", "Honolulu"],
        student: ["elementary student", "middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Redemption Academy",
        yelpName: "redemption-academy-honolulu-2",
        image: "/assets/images/c.png",
        category: "schools",
        address: "423 Kamakee Street Honolulu, HI 96814",
        telephone: "(808) 591-7701",
        website: "www.redemptionacademy.org",
        gradeLevels: "K - 12",
        enrollment: "59",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Honolulu"],
        student: ["elementary student", "middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Sacred Hearts Academy",
        yelpName: "sacred-hearts-academy-honolulu",
        image: "/assets/images/d.png",
        category: "schools",
        address: "3253 Waialae Avenue Honolulu, HI 96816",
        telephone: "(808) 734-5058 ext. 224",
        website: "www.sacredhearts.org",
        gradeLevels: "PK - 12",
        enrollment: "987",
        boarding: "Day Only",
        gender: "Girls Only",
        religion: "Roman Catholic",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student", "middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Saint Francis School",
        yelpName: "saint-francis-school-honolulu?osq=st+francis+school",
        image: "/assets/images/e.png",
        category: "schools",
        address: "2707 Pamoa Road Honolulu, HI 96822",
        telephone: "(808) 988-4111 ext. 701",
        website: "www.stfrancis-oahu.org",
        gradeLevels: "EC - 12",
        enrollment: "544",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student", "middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Saint Louis School",
        yelpName: "saint-louis-school-honolulu-2?osq=st+louis+school",
        image: "/assets/images/f.png",
        category: "schools",
        address: "3142 Waialae Avenue Honolulu, HI 96816-1579",
        telephone: "(808) 739-7777",
        website: "www.saintlouishawaii.org",
        gradeLevels: "6 - 12",
        enrollment: "550",
        boarding: "Day Only",
        gender: "Boys Only",
        religion: "Roman Catholic",
        town: ["any town", "Honolulu"],
        student: ["middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Saint Mark Lutheran School",
        yelpName: "saint-mark-lutheran-school-kaneohe",
        image: "/assets/images/g.png",
        category: "schools",
        address: "45-725 Kamehameha Hwy. Kaneohe, HI 96744",
        telephone: "(808) 247-5589",
        website: "www.smls-hawaii.org",
        gradeLevels: "K - 8",
        enrollment: "208",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Lutheran",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "St. Andrews Priory School",
        yelpName: "st-andrews-priory-school-honolulu?osq=st+andrews+schools",
        image: "/assets/images/h.png",
        category: "schools",
        address: "224 Queen Emma Square Honolulu, HI 96813",
        telephone: "(808) 536-6102",
        website: "www.standrewsschools.org",
        gradeLevels: "K - 12",
        enrollment: "355",
        boarding: "Day Only",
        gender: "Girls Only",
        religion: "Episcopal",
        town: ["any town", "Honolulu"],
        student: ["elementary student", "middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "St. Ann's Model School",
        yelpName: "",
        image: "/assets/images/i.png",
        category: "schools",
        address: "46-125 Haiku Road Kaneohe, HI 96744",
        telephone: "(808) 247-3092",
        website: "www.stannshi.org",
        gradeLevels: "PK - 8",
        enrollment: "425",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "St. Anthony School",
        yelpName: "",
        image: "/assets/images/j.png",
        category: "schools",
        address: "148 Makawao St. Kailua HI 96734",
        telephone: "(808) 261-3331",
        website: "saskailua.org",
        gradeLevels: "PK - 8",
        enrollment: "338",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Kailua", "Kaneohe"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kailua",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "St. Anthony School",
        yelpName: "",
        image: "/assets/images/k.png",
        category: "schools",
        address: "640 Puuhale Road Honolulu, HI 96819",
        telephone: "(808) 845-3255",
        website: "www.saintanthonyschoolhonolulu.com",
        gradeLevels: "K - 8",
        enrollment: "110",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Honolulu"],
        student: ["elementary student", "middle schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "St. Clements School",
        yelpName: "st-clements-school-honolulu",
        image: "/assets/images/l.png",
        category: "schools",
        address: "1515 Wilder Avenue Honolulu, HI 96822-4614",
        telephone: "(808) 949-2082",
        website: "http://www.stclementsschoolhawaii.com",
        gradeLevels: "PK - K",
        enrollment: "126",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Episcopal",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "St. Elizabeth School",
        yelpName: "st-elizabeth-school-and-church-aiea",
        image: "/assets/images/m.png",
        category: "schools",
        address: "99-310 Moanalua Road Aiea, HI 96701",
        telephone: "(808)487-2414",
        website: "www.steliz-hi.org",
        gradeLevels: "K - 8",
        enrollment: "254",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Aiea", "Pearl City"],
        student: ["elementary student", "middle schooler"],
        city: "Aiea",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "St. John the Baptist School",
        yelpName: "st-john-the-baptist-honolulu",
        image: "/assets/images/n.png",
        category: "schools",
        address: "2340 Omilo Lane Honolulu, HI 96819",
        telephone: "(808)841-5551",
        website: "",
        gradeLevels: "PK - 8",
        enrollment: "255",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "St. John's Catholic Preschool",
        yelpName: "st-johns-catholic-preschool-mililani",
        image: "/assets/images/o.png",
        category: "schools",
        address: "95-370 Kuahelani Ave. Mililani, HI 96789",
        telephone: "(808)623-3332",
        website: "www.stjohnmililani.org",
        gradeLevels: "PK - K",
        enrollment: "75",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Mililani"],
        student: ["preschooler", "elementary student"],
        city: "Mililani",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "St. Joseph School",
        yelpName: "st-joseph-school-waipahu",
        image: "/assets/images/p.png",
        category: "schools",
        address: "94-651 Farrington Hwy. Waipahu, HI 96797",
        telephone: "(808) 677-4475",
        website: "www.stjosephwaipahu.org",
        gradeLevels: "PK - 8",
        enrollment: "440",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Waipahu"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Waipahu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "St. John Vianney School",
        yelpName: "",
        image: "/assets/images/a.png",
        category: "schools",
        address: "940 Keolu Drive Kailua, HI 96734",
        telephone: "(808) 261-4349",
        website: "www.sjvparishschoolhawaii.org",
        gradeLevels: "PK - 8",
        enrollment: "293",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Kailua", "Kaneohe"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kailua",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "St. Michael School",
        yelpName: "st-michaels-school-waialua",
        image: "/assets/images/b.png",
        category: "schools",
        address: "67-340 Haona St. Waialua, HI 96791",
        telephone: "(808) 637-7772",
        website: "www.lava.net/~smshark",
        gradeLevels: "PK - 8",
        enrollment: "251",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Waialua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Waialua",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "St. Patrick School",
        yelpName: "st-patrick-school-honolulu",
        image: "/assets/images/c.png",
        category: "schools",
        address: "3320 Harding Ave. Honolulu, HI 96816",
        telephone: "(808) 734-8979",
        website: "www.spatschool.org",
        gradeLevels: "K - 8",
        enrollment: "465",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "St. Philomenas Early Learning Center",
        yelpName: "st-philomenas-early-learning-center-honolulu-2",
        image: "/assets/images/d.png",
        category: "schools",
        address: "3300 Ala Laulani Street Honolulu, HI 96818",
        telephone: "(808) 833-8080",
        website: "www.spelc-hawaii.com",
        gradeLevels: "EC - K",
        enrollment: "180",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "St. Theresa School",
        yelpName: "st-theresas-school-honolulu",
        image: "/assets/images/e.png",
        category: "schools",
        address: "712 N. School St. Honolulu, HI 96817",
        telephone: "(808) 536-4703",
        website: "",
        gradeLevels: "K - 8",
        enrollment: "481",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Honolulu"],
        student: ["elementary student", "middle schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "St. Timothy's Children's Center",
        yelpName: "",
        image: "/assets/images/f.png",
        category: "schools",
        address: "98-939 Moanalua Road Aiea, HI 96701",
        telephone: "(808) 488-1766",
        website: "www.st-timsofoahu.org",
        gradeLevels: "PK - 1",
        enrollment: "123",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Episcopal",
        town: ["any town", "Aiea", "Pearl City"],
        student: ["preschooler", "elementary student"],
        city: "Aiea",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Soto Academy",
        yelpName: "soto-academy-honolulu",
        image: "/assets/images/g.png",
        category: "schools",
        address: "1708 Nuuanu Avenue Honolulu, HI 96817",
        telephone: "(808) 533-0452",
        website: "www.sotoacademy.org",
        gradeLevels: "K - 6",
        enrollment: "79",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Nondenominational",
        town: ["any town", "Honolulu"],
        student: ["elementary student"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Star of the Sea School",
        yelpName: "star-of-the-sea-schools-honolulu",
        image: "/assets/images/h.png",
        category: "schools",
        address: "4469 Malia St. Honolulu, HI 96821",
        telephone: "(808) 734-3840",
        website: "www.starofthesea.org",
        gradeLevels: "PK - 8",
        enrollment: "256",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Star of the Sea School Early Learning Center",
        yelpName: "star-of-the-sea-schools-honolulu",
        image: "/assets/images/i.png",
        category: "schools",
        address: "4470 Aliikoa Street, #100 Honolulu, HI 96821",
        telephone: "(808) 734-3840",
        website: "www.staroftheseaelc.org",
        gradeLevels: "EC - K",
        enrollment: "170",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Roman Catholic",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Sunset Beach Christian School",
        yelpName: "",
        image: "/assets/images/j.png",
        category: "schools",
        address: "59-578 Kamehameha Hwy. Haleiwa, HI 96712",
        telephone: "(808) 638-8274",
        website: "www.sbcshome.com",
        gradeLevels: "K - 8",
        enrollment: "65",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Haleiwa"],
        student: ["elementary student", "middle schooler"],
        city: "Haleiwa",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "The Cole Academy",
        yelpName: "cole-academy-honolulu-2",
        image: "/assets/images/k.png",
        category: "schools",
        address: "36 Merchant St. Downtown, HI 96813",
        telephone: "(808) 531-4500",
        website: "www.thecoleacademy.com",
        gradeLevels: "PK",
        enrollment: "125",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Nondenominational",
        town: ["any town", "Honolulu"],
        student: ["preschooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "The Cole Academy",
        yelpName: "cole-academy-waipahu",
        image: "/assets/images/l.png",
        category: "schools",
        address: "94-673 Kupuohi St. Kunia, HI 96797",
        telephone: "(808) 677-4488",
        website: "www.thecoleacademy.com",
        gradeLevels: "PK",
        enrollment: "100",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Nondenominational",
        town: ["any town", "Ewa Beach"],
        student: ["preschooler"],
        city: "Ewa Beach",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "The Cole Academy",
        yelpName: "cole-academy-honolulu",
        image: "/assets/images/m.png",
        category: "schools",
        address: "1041 10th Ave. Kaimuki, HI 96816",
        telephone: "(808) 732-4200",
        website: "www.thecoleacademy.com",
        gradeLevels: "PK",
        enrollment: "140",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Nondenominational",
        town: ["any town", "Honolulu"],
        student: ["preschooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Trinity Lutheran School",
        yelpName: "trinity-lutheran-school-wahiawa-wahiawa",
        image: "/assets/images/n.png",
        category: "schools",
        address: "1611 California Avenue Wahiawa, HI 96786",
        telephone: "(808) 621-6033",
        website: "www.trinity-hawaii.org",
        gradeLevels: "PK - 8",
        enrollment: "220",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Lutheran",
        town: ["any town", "Wahiawa"],
        student: ["elementary student", "middle schooler"],
        city: "Wahiawa",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Trinity Christian School",
        yelpName: "trinity-christian-school-kailua",
        image: "/assets/images/o.png",
        category: "schools",
        address: "875 Auloa Road Kailua, HI 96734",
        telephone: "(808) 262-8501",
        website: "www.TCSKailua.net",
        gradeLevels: "PK - 12",
        enrollment: "356",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Presbyterian",
        town: ["any town", "Kailua", "Kaneohe"],
        student: ["preschooler", "elementary student", "middle schooler", "high schooler"],
        city: "Kailua",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Variety School of Hawaii",
        yelpName: "variety-school-of-hawaii-honolulu",
        image: "/assets/images/p.png",
        category: "schools",
        address: "710 Palekaua Street Honolulu, HI 96816",
        telephone: "(808) 732-2835",
        website: "www.varietyschool.org",
        gradeLevels: "K - 10",
        enrollment: "45",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Independent",
        town: ["any town", "Honolulu"],
        student: ["elementary student", "middle schooler", "high schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Waolani Judd Nazarene School",
        yelpName: "waolani-judd-nazarene-school-honolulu",
        image: "/assets/images/a.png",
        category: "schools",
        address: "408 North Judd Street Honolulu, HI 96817",
        telephone: "(808) 531-5251 ext. 302",
        website: "www.wjns.org",
        gradeLevels: "PK - 8",
        enrollment: "208",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Honolulu"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Honolulu",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Windward Adventist School",
        yelpName: "",
        image: "/assets/images/b.png",
        category: "schools",
        address: "160 Mookua St. Kailua, HI 96734",
        telephone: "(808) 261-0565",
        website: "",
        gradeLevels: "K - 8",
        enrollment: "60",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kailua", "Kaneohe"],
        student: ["elementary student", "middle schooler"],
        city: "Kailua",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Windward Nazarene Academy",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/c.png",
        category: "schools",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "www.wnahawaii.com/",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        writeUp: "At WNA we encourage your child to explore — to create — to learn new concepts. Learning by doing motivates preschoolers. The curriculum at WNA is well-rounded — art, music, iPads, even sustainable gardening take their place next to language, math and social studies. Learning is meant to be fun at WNA. From Preschool to Elementary and Intermediate grades (up to grade 8), our students are taught important life skills in a safe, nurturing Christian environment. Our goal is to expand their knowledge and skills while creating lifetime experiences.",
        logo: "../assets/images/wna-logo.png"
      }, {
        /* --------------------- ACTIVES  --------------------- */
        name: "Lanikai Beach",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/lanikai.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Sandy Beach",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/sandys.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Daimond Head Beach",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/daimondheadbeach.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Waimea Bay",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/waimea.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Kailua Beach",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/kailua.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Wet N' Wild Water Park",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/wetnwild.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Maunawili Falls Trailhead",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/maunawili.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Kokohead Hike",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/kokohead.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Daimond Head Hike",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/daimondheadhike.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Kayak to Mokulua Islands",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/kayak.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Hanauma Bay",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/hanauma.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Stand Up Paddle Board at Anahulu River",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/anahulu.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Pali Lookout",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/pali.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Kuliouou Hike",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/kuliouou.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Skydive Hawaii",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/skydive.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Hawaii Loa Ridge Hike",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/hawaiiloaridge.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Sea Life Park",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/sealifepark.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Honolulu Zoo",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/zoo.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Honolulu Aquarium",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/aquarium.jpg",
        category: "actives",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        /* ------------------- ENRICHMENTS  -------------------- */
        name: "Branch Studios Hawaii",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/branch.jpg",
        category: "enrichments",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Pas De Deux",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/pasdedeux.jpg",
        category: "enrichments",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, { 
        name: "Na Maka",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/namaka.jpg",
        category: "enrichments",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Leahi Swim School",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/leahi.jpg",
        category: "enrichments",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        name: "Kumon of Hawaii Kai",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/kumon.jpg",
        category: "enrichments",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, { 
        name: "TLC for Kids School",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/TLC.jpg",
        category: "enrichments",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
      }, {
        /* --------------------- CULTURES  ---------------------- */
        name: "Iolani Palace",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/iolani.jpg",
        category: "cultures",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
    }, {
        name: "Bishop Museum",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/bishop.jpg",
        category: "cultures",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
    }, { 
        name: "Polynesian Culture Center",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/pcc.jpg",
        category: "cultures",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
    }, {
        name: "Hawaii Children's Discovery Center",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/discovery.jpg",
        category: "cultures",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
    }, {
        name: "Pacific Aviation Museum",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/aviation.jpg",
        category: "cultures",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
    }, { 
        name: "Hawaii Nature Center",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/nature.jpg",
        category: "cultures",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
    }, {
        /* ---------------------- HEALTHS  ---------------------- */
        name: "Dr. Brent Uyeno",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/uyeno.jpg",
        category: "healths",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
    }, {
        name: "Dr. Dean Sueda",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/sueda.jpg",
        category: "healths",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
    }, {
        name: "Dr. Shigezawa",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/shigezawa.jpg",
        category: "healths",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
    }, {
        /* ---------------------- FOODS  ---------------------- */
        name: "Great Harvest Bakery",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/greatharvest.jpg",
        category: "foods",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
    }, {
        name: "Liliha Bakery",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/liliha.jpg",
        category: "foods",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
    }, {
        name: "Zippy's",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/zippys.jpg",
        category: "foods",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
    }, {
        name: "Gyotaku Japanese Restaurant",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/gyotaku.jpg",
        category: "foods",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
    }, {
        name: "Shokudo Japanese Restaurant",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/shokudo.jpg",
        category: "foods",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
    }, {
        name: "Moon Garden",
        yelpName: "windward-nazarene-academy-kaneohe",
        image: "/assets/images/moon.jpg",
        category: "foods",
        address: "45-232 Puaae Road, P.O.Box 1633 Kane'ohe, HI 96744",
        telephone: "(808) 235-8787 ext. 200",
        website: "windwardnazarene.com",
        gradeLevels: "PK - 8",
        enrollment: "171",
        boarding: "Day Only",
        gender: "Co-ed",
        religion: "Christian",
        town: ["any town", "Kaneohe", "Kailua"],
        student: ["preschooler", "elementary student", "middle schooler"],
        city: "Kaneohe",
        logo: "../assets/images/sja-logo.jpg"
    });
});

// User.find({}).remove(function() {
//   User.create({
//     provider: 'local',
//     name: 'Test User',
//     email: 'test@test.com',
//     password: 'test'
//   }, {
//     provider: 'local',
//     role: 'admin',
//     name: 'Admin',
//     email: 'admin@admin.com',
//     password: 'admin'
//   }, function() {
//       console.log('finished populating users');
//     }
//   );
// });




